### ISSUE TITLE
JavaScript error when launching (Windows)

### ISSUE THREAD

**Issue by he3als** [ArmCord/ArmCord#56]
![image](https://user-images.githubusercontent.com/65787561/134030034-3076f7ff-47cd-468e-ad92-aca334b0754d.png)
When launching ArmCord on Windows, you first get this error. You need to click OK then relaunch ArmCord. After that you get this error.
![image](https://user-images.githubusercontent.com/65787561/134030144-b0f32773-dd79-4c37-a06a-df504d48c3ed.png)
Is this GooseMod failing to inject/work? You can just click OK though and everything works (except GooseMod).

**Comment by smartfrigde** [comment]
Related to #55
It seems that GooseMod download has failed and became corrupted. To manually fix this issue do the following:
- Download https://github.com/GooseMod/Extension as a zip, 
- Extract it in %appdata%\ArmCord\plugins
- Restart your client from tray.
GooseMod fixes loading external css/fonts due to how it manages CSP. In short discord blocks everyone from embedding css and fonts from domains that are not discord.com. GooseMod is bypassing it.

**Comment by he3als** [comment]
It happened for 3 people though

**Comment by smartfrigde** [comment]
Downloading is hit or miss. It'll be fixed in next update

**Comment by smartfrigde** [comment]
Fixed in latest release which is currently building.
